import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "../globals.css";
import { HomeNavbar } from "@/components/navbar/HomeNavbar";
import { HomeFooter } from "@/components/footer/HomeFooter";

const RobotoSans = Roboto({
  variable: "--font-custom-sans",
  subsets: ["latin"],
});

const RobotoMono = Roboto_Mono({
  variable: "--font-custom-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${RobotoSans.variable} ${RobotoMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <HomeNavbar />
        {children}
        <HomeFooter/>
      </body>
    </html>
  );
}
